name: music_player
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  hooks_riverpod:
  flutter_bloc:
  shared_preferences:
  flutter_screenutil:

  firebase_auth:
  firebase_core:
  firebase_storage:
  # cloud_firestore:
  cloud_firestore: ^4.14.0

  audioplayers: ^6.0.0
  intl: ^0.19.0
  just_audio: ^0.9.36

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audios/
    - assets/fonts/



  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
          style: italic
  
